import './bootstrap';
import swal from 'sweetalert';
window.swal = swal;
import Fireworks from 'fireworks-js';
window.Fireworks = Fireworks;
import AutoNumeric from 'autonumeric';
window.AutoNumeric = AutoNumeric;
import SlimSelect from 'slim-select';
import 'slim-select/styles';
window.SlimSelect = SlimSelect;