import { Button, Card, Descriptions, Image, Progress, Table, Tag, Typography } from 'antd';
import { ArrowLeftOutlined, EditOutlined } from '@ant-design/icons';

const { Text, Title, Paragraph } = Typography;
const formatDate=(value)=>value?new Intl.DateTimeFormat('vi-VN',{dateStyle:'short',timeStyle:'short'}).format(new Date(value)):'—';

export default function FeatureAnnouncementShowPage({ config }) {
    const a=config.announcement||{}; const stats=config.stats||{}; const users=stats.users||[];
    const percent=Number(stats.target_count||0)>0?Math.round(Number(stats.acknowledged_count||0)*100/Number(stats.target_count)):0;
    const columns=[{title:'Người nhận',render:(_,row)=><div><Text strong>{row.user?.full_name||row.user?.username}</Text><div><Text type="secondary">@{row.user?.username} · {config.roleLabels?.[row.user?.role]||row.user?.role}</Text></div></div>},{title:'Email',render:(_,row)=>row.user?.email||'—'},{title:'Trạng thái',render:(_,row)=>row.acknowledged_at?<Tag color="success">Đã xác nhận</Tag>:<Tag>Chưa xác nhận</Tag>},{title:'Thời gian',render:(_,row)=>row.acknowledged_at?formatDate(row.acknowledged_at):'—'}];
    return <div className="container-fluid px-4 pb-5"><Button icon={<ArrowLeftOutlined/>} href={config.routes.index} className="mb-3">Quay lại danh sách</Button><div className="d-flex justify-content-between gap-3 mb-4"><div><Title level={2}>{a.title}</Title><Text type="secondary">Version {a.version} · {stats.acknowledged_count||0}/{stats.target_count||0} người đã xác nhận</Text></div>{config.permissions?.update&&<Button type="primary" icon={<EditOutlined/>} href={config.routes.edit}>Chỉnh sửa</Button>}</div><div className="row"><div className="col-lg-8 mb-4"><Card title="Nội dung"><Paragraph style={{whiteSpace:'pre-wrap'}}>{a.content}</Paragraph>{a.image_path&&<Image src={`${String(config.storageBaseUrl||'/storage').replace(/\/$/,'')}/${a.image_path}`} style={{maxHeight:360,objectFit:'contain'}}/>}{a.action_url&&<div className="mt-3"><Button href={a.action_url} target="_blank">{a.action_text||'Mở liên kết'}</Button></div>}</Card></div><div className="col-lg-4 mb-4"><Card title="Thông tin"><Descriptions column={1} size="small"><Descriptions.Item label="Ưu tiên">{a.priority}</Descriptions.Item><Descriptions.Item label="Bắt đầu">{formatDate(a.starts_at)}</Descriptions.Item><Descriptions.Item label="Kết thúc">{a.ends_at?formatDate(a.ends_at):'Không giới hạn'}</Descriptions.Item><Descriptions.Item label="Đối tượng">{a.target_type==='users'?`${a.targeted_users?.length||0} tài khoản`:(a.target_roles||[]).map(r=>config.roleLabels?.[r]||r).join(', ')}</Descriptions.Item></Descriptions><Progress percent={percent}/></Card></div></div><Card title="Báo cáo xác nhận"><Table rowKey={(row)=>row.user?.id} dataSource={users} columns={columns} pagination={{pageSize:10}}/></Card></div>;
}
